### PR TITLE
Upgrade YAML requirements

### PR DESCRIPTION
**Pull request by agatemosu**
I can't install PyYAML so I need this

### CODE REVIEW

**Comment by agatemosu** [comment]
I also wonder if It can be more lenient with the versions

**Comment by TicClick** [comment]
this shouldn't happen, can you explain what exactly you do and post which errors you receive? 

normally you would make a virtual environment and install all the packages you need into it, including osu-wiki-tools

**Comment by agatemosu** [comment]
I get this:

<details><summary>Terminal output</summary>

```
~ $ pip install pyyaml==6.0                             Collecting pyyaml==6.0
  Using cached PyYAML-6.0.tar.gz (124 kB)                 Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error                                                                             × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO                    writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt                                                    Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()                                                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9bdkpc5l/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

</details>

**Comment by TicClick** [comment]
not sure what your setup is (OS, and Python distribution -- `which pip; pip --version`), but this seems to be an issue for a specific combination of PyYAML + OS + interpreter, where `pip` cannot compile an installation package from ground up. I'd usually recommend installing `python3-dev` and retrying, but there seems to be more than that:
- https://github.com/yaml/pyyaml/issues/601
- https://github.com/pytorch/pytorch/pull/115956

> I also wonder if It can be more lenient with the versions

technically yes, since `>=` exists, but I'd argue that dependency pinning ensures stability

**Review by TicClick — APPROVED** [review]
all in all, I'm in favour of dependency bumps anyway

**Comment by Walavouchey** [comment]
this'll be in the next release whenever that happens, unless this is somehow required atm. use your local build for now

**Pull request merged**
